### ISSUE TITLE
SMALL TASKS

### ISSUE THREAD

**Issue by andrtechno** [polserver/ClassicDistro#21]
This ticket is for small tasks that I will publish here. In order not to pay a lot of small tasks

**Comment by andrtechno** [comment]
include/npccast.inc
GetSpellID()
here you need to replace the capital letters of magic with ordinary ones. (greaterHeal > greaterheal) etc

**Comment by andrtechno** [comment]
pkg/skills/magery/spells/circle1/clumsy.src
duplicate
`SetObjProperty(cast_on, "LastHit", {caster.name,caster.serial, "clumsy" });`

**Comment by andrtechno** [comment]
pkg/skills/magery/spells/circle1/feeblemind.src
duplicate string
`SetObjProperty(cast_on, "LastHit", {caster.name,caster.serial, "feeblemind" });`

**Comment by andrtechno** [comment]
spell > greaterheal
no sound and object effects

**Comment by andrtechno** [comment]
**magic reflection**
exactly the same effects should be?
`
PlaySoundEffect(caster,0x005d);
PlayObjectCenteredEffect(caster, 0x3735,0x0a, 0x1e);
`

**Comment by Admin-Yukiko** [comment]
I fixed all but the last one. When posting issues, if you can post the section of the code where the issue is, that would be helpful. If you want to make the changes yourself and commit them to your fork, you can do a pull request to have your fixes added to the Classic Distro.

I commented out the spell fizzles sound in magic reflection because I could not find a sound for removing magic reflect.
