### ISSUE TITLE
runebook recall&gate target

### ISSUE THREAD

**Issue by andrtechno** [polserver/ClassicDistro#7]
runebook (pkg/items/runebook). there, when you click on Recall and Gate, a target with magic appears

**Comment by Admin-Yukiko** [comment]
I am working on this. It is requiring some changes to a few scripts. I am almost certain this bug also exists in the official Distro as well because the runebook script is the same in both Distros. If so this is one of those "killing two birds with one stone" events. Thank you for discovering this issue.

**Comment by andrtechno** [comment]
maybe in modern, I didn’t even look at modern..
I found a lot of mistakes here, both big and small. but I didn't report them

**Comment by Admin-Yukiko** [comment]
Fixed this issue in latest commit.
